#!/bin/bash

running=$(pgrep python)
IP=$(ifconfig | awk '/inet addr/{print substr($2,6)}' | sed -n "2"p)

# colors
red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

if [ "$1" = "--status" ]; then
	if [ "$running" = "" ]; then
		echo 'Status(transfer-x): Inactive'
	else
		echo 'Status(transfer-x): Active'
		echo "http://$IP:8000/transfer-box.zip"
	fi
	exit 0
fi

if [ "$1" = "--stop" ]; then
	if [ "$running" != "" ]; then
		kill -9 $running
		echo 'Server is stopped!'
		echo 'Hey! The Tranfer is done! Firewall will be up now'
		sudo ufw enable
		rm -f transfer-box.zip
	else
		echo 'Sorry! transfer-x is not running'
	fi
	exit 0
fi

if [ "$1" = "--help" ]; then
	echo 'Hello, transfer-x is used to transfer files or folders in a same network by zipping them'
	echo "to add files/folders to be sent          : ${red}transfer-x <file or folder> <file or folder> ...${reset}"
	echo "to stop transfer-x server                : ${red}transfer-x --stop${reset}"
	echo "to check the status of transfer-x server : ${red}transfer-x --status${reset}"
	echo "to get help for transfer-x commands      : ${red}transfer-x --help${reset}"
	exit 0
fi

if [ "${1:0:2}" = "--" ]; then
	echo 'Unknown command'
	echo "type ${red}trasfer-x --help${reset}"
	exit 0
fi

if [ $# -eq 0 ]; then
	echo 'Hey! What to trasfer?'
	echo "type ${red}trasfer-x --help${reset}"
	exit 0
fi

if [ "$running" != "" ]; then
	echo 'Already transfer-x server is running'
	echo "type ${red}transfer-x --stop${reset} to stop the server"
	exit 0
fi

rm -f tranfer-box.zip
rm -rf transfer-box
mkdir transfer-box
for arg in $@; do
	if [ -f "$arg" ] || [ -d "$arg" ]; then
		cp -rf $arg transfer-box/$arg
	else
		echo "unrecognized: \"$arg\" is ignored"
	fi
done

if [ "$(ls -A transfer-box)" = "" ]; then
	echo 'Nothing added.'
	exit 0
fi

zip -r transfer-box.zip transfer-box
rm -rf transfer-box
echo

echo 'Hey! Just want to off the firewall till the tranfer is done!'
sudo ufw disable

/usr/bin/python -m SimpleHTTPServer > /dev/null 2>&1 &
echo
echo 'Hi! The server is running!'
echo
echo -e "\033[93m http://$IP:8000/transfer-box.zip \033[00m"
echo
echo '** Paste the link in receiver browser **'
echo
