#!/bin/bash

running=$(pgrep python)

if [ "$1" = "--status" ]; then
	if [ "$running" = "" ]; then
		echo 'Status(transfer-x): Inactive'
	else
		echo 'Status(transfer-x): Active'
	fi
	exit 0
fi

if [ "$1" = "--stop" ]; then
	if [ "$running" != "" ]; then
		kill -9 $running
		echo 'Hey! The Tranfer is done! Firewall will be up now'
		sudo ufw enable
		rm -f transfer-box.zip
	else
		echo 'Sorry! transfer-x is not running'
	fi
	exit 0
fi

if [ "$1" = "--help" ]; then
	echo 'Hello, transfer-x is used to transfer files or folders in a same network by zipping them'
	echo 'to add files/folders to be sent          : transfer-x <file or folder> <file or folder> ...'
	echo 'to stop transfer-x server                : transfer-x --stop'
	echo 'to check the status of transfer-x server : transfer-x --status'
	echo 'to get help for transfer-x commands      : transfer-x --help'
	exit 0
fi

if [ "${1:0:2}" = "--" ]; then
	echo 'Unknown command'
	echo 'type trasfer-x --help'
	exit 0
fi

if [ $# -eq 0 ]; then
	echo 'Hey! What to trasfer?'
	echo 'type trasfer-x --help'
	exit 0
fi

rm -f tranfer-box.zip
mkdir transfer-box
for arg in $@; do
	cp -rf $arg transfer-box/$arg
done
zip -r transfer-box.zip transfer-box
rm -rf transfer-box
echo

echo 'Hey! Just want to off the firewall till the tranfer is done!'
sudo ufw disable

python -m SimpleHTTPServer > /dev/null 2>&1 &
echo 'Hi! The server is running!'

